### ISSUE TITLE
uhuruchat web widget templating and configuration

### ISSUE THREAD

**Issue by imtiaz-rahi** [uhurutek/uchat-widget#1]
- [x] widget frontend customization based on customer setup
- [x] Ensure all necessary headers, referrers are send to API backend for appropriate logging

Takes configuration from database (?) and provide easy integration UCBOT_KEY and UCSITE_KEY is configured

**Comment by bm-alamin** [comment]
@shant00 please move this task to sprint 1. Because we need widget to test coversation apis and embed website

**Comment by shant00** [comment]
/uhuruchat/bots/{bot_id} (getting bot details)
/chat/{conversation_id} (post call new conversation)

/chat/{converstion_id} (PATCH call to continue messaging also need to send conversion_id)


Need to take unique identifier from pc/browser/hardware/os and other information  or MAC address, set cookie  at browser

Question: 
1. How do we manage history?
2. How can we manage previous chats?

**Comment by shant00** [comment]
Task Summary:

1. Allow users to customize this widget according to their color preferences.
2. Enable users to set their logo.
3. Retrieve basic details of the end-user (IP address, user agent, operating system, browser, etc.).
4. Generate a unique ID and store it in local storage to identify the end-user.

Please note that testing isn't possible at the moment due to the unavailability of the API and its integration. You can access the code on the 'widget-final' branch.
